import { Inter } from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next.js App',
	description: 'Generated by create next app',
};

// Динамически загружаем ProviderWrapper, чтобы он рендерился только на клиенте
const ProviderWrapper = dynamic(() => import('@/components/header/ProviderWrapper'), { ssr: false });

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ProviderWrapper>
					{children}
				</ProviderWrapper>
				<div id={'modal-root'}></div>
			</body>
		</html>
	);
}
